# Generated by Django 2.2.4 on 2020-03-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='email',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='destination',
            name='name',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='destination',
            name='password',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
