# Generated by Django 2.2.4 on 2020-03-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_page', '0002_auto_20200319_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='destination',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
    ]
