# Generated by Django 2.2.4 on 2020-04-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_page', '0008_auto_20200410_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='post1',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
