# Generated by Django 2.2.4 on 2020-04-12 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_page', '0009_post1_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post1',
            name='count',
        ),
    ]
