# Generated by Django 2.2.4 on 2020-04-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_page', '0010_remove_post1_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post1',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
