# Generated by Django 2.2.4 on 2020-04-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_page', '0011_post1_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('num', models.IntegerField(default=0)),
            ],
        ),
    ]
