# Generated by Django 2.2.4 on 2020-04-12 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_page', '0012_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comment',
            new_name='comment1',
        ),
    ]
