# Generated by Django 2.2.4 on 2020-04-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_page', '0015_auto_20200414_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='post1',
            name='spam',
            field=models.IntegerField(default=0),
        ),
    ]
